apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  name: {{ include "mlaas-ui.fullname" . }}-pull
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}
type: kubernetes.io/dockerconfigjson
