apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlaas-ui.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "auth-service.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: "{{ .Chart.Name }}"
    environment: "{{ .Values.environment }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "auth-service.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
